from flask import Flask
from flask import request

app = Flask(__name__)


@app.route('/find')
def find():
    import base64
    img = request.args['img']
    base64.b64decode(img)
    # process image
    pass


@app.route('/index')
def index():
    vk = request.args['vk']
    # index user, process photos
    pass


@app.route('/result')
def result():
    id_ = request.args['id']
    # response with csv generated by create_csv
    pass


if __name__ == '__main__':
    app.run()
